#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ast
Version  : 2.3.0
Release  : 9
URL      : https://rubygems.org/downloads/ast-2.3.0.gem
Source0  : https://rubygems.org/downloads/ast-2.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-bacon-colored_output
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-docile
BuildRequires : rubygem-json_pure
BuildRequires : rubygem-kramdown
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-yard

%description
# AST
[![Build Status](https://travis-ci.org/whitequark/ast.svg?branch=master)](https://travis-ci.org/whitequark/ast)
[![Code Climate](https://codeclimate.com/github/whitequark/ast.svg)](https://codeclimate.com/github/whitequark/ast)
[![Coverage Status](https://coveralls.io/repos/whitequark/ast/badge.svg?branch=master)](https://coveralls.io/r/whitequark/ast)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ast-2.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-ast.gemspec

%build
export LANG=C
gem build rubygem-ast.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ast-2.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ast-2.3.0
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ast-2.3.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/LICENSE.MIT
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/README.YARD.md
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/ast.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/.last_run.json
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/.resultset.json
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/.resultset.json.lock
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/application.css
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/application.js
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/colorbox/border.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/colorbox/controls.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/colorbox/loading.gif
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/colorbox/loading_background.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/favicon_green.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/favicon_red.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/favicon_yellow.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/loading.gif
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/magnify.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_dadada_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-icons_222222_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-icons_2e83ff_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-icons_454545_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-icons_888888_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/assets/0.10.0/smoothness/images/ui-icons_cd0a0a_256x240.png
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/coverage/index.html
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast.rb
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/processor/mixin.rb
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/lib/ast/sexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ast-2.3.0/test/test_ast.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ast-2.3.0.gemspec
